djangoplayer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_nation.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music_nation/urls.py
from django.urls import path, include, re_path
from . import views as music_nation_views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'music_nation'
urlpatterns = [
    #home /
    path('', music_nation_views.home, name='home'),

    #profile_detail /@username/
    path('@<str:username>/', music_nation_views.profile_detail, name='profile_detail'),

    #add new album /@username/add
    path('@<str:username>/add/', music_nation_views.add_album, name='add_album'),

    #album's detail page /@username/album/album_name
    path('@<str:username>/album/<str:album>/', music_nation_views.album_detail, name='album_detail'),

    # login the user /login/
    path('login/', LoginView.as_view(template_name='music_nation/login.html'), name="login"),

    # signUp new user /signup/
    path('signup/', music_nation_views.signup, name='signup'),

    #delete album /@username/album/album_name/delete
    path('@<str:username>/album/<str:album>/delete/', music_nation_views.delete_album, name='delete_album'),

    #add songs to the albums
    path('@<str:username>/album/<str:album>/add/', music_nation_views.add_song, name='add_song'),

    #logout the current user
    path('logout/', LogoutView.as_view(), name='logout'),
]
#path('link', view, name='', kwargs={})
#re_path(r'regex', view, name='', kwargs={})

music_nation/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from djangoplayer.settings import MEDIA_ROOT

def user_directory_path(self, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(self.album_artist.id, filename)

def user_directory_path_song(self, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>

    return 'user_{0}/{1}'.format(self.song_album.album_artist.id, filename)

# Create your models here.
class Album(models.Model):
    album_name = models.CharField(max_length=30)
    uploaded_on = models.DateField(default=timezone.now())
    album_logo = models.FileField(upload_to=user_directory_path)
    album_genre = models.CharField(max_length=30)
    album_artist = models.ForeignKey(User, on_delete=models.CASCADE, related_name='albums')

    def __str__(self):
        return self.album_name

    def delete_media(self):
        os.remove(path=MEDIA_ROOT+'/'+str(self.album_logo))




class Song(models.Model):
    song_name = models.CharField(max_length=40)
    song_album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name='songs')
    song_file = models.FileField(upload_to=user_directory_path_song)

    def __str__(self):
        return self.song_name +' '+ str(self.song_album)

    def delete_media(self):
        os.remove(path=MEDIA_ROOT+'/'+str(self.song_file))

music_nation/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Album, Song

class NewAlbum(forms.ModelForm):

    class Meta:
        model = Album
        fields = ('album_name','album_genre','album_logo',)

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required='True')
    first_name = forms.CharField(required='True')
    last_name = forms.CharField(required='True')

    class meta:
        model = User
        fields = (
        'first_name',
        'last_name',
        'email',
        'username',
        'password1',
        'password2',
        )

    def save(self, commit='True'):
        user = super(SignUpForm, self).save(commit='False')
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']


        if commit:
            user.save()
        return user

class NewSong(forms.ModelForm):

    class Meta:
        model = Song
        fields = ('song_name','song_file',)

music_nation/views.py
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect
    )
from django.utils import timezone
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django import forms

from .forms import SignUpForm
from .models import Album, Song
from .forms import NewAlbum, NewSong

import logging

##########################################################

logger = logging.getLogger(__name__)

def home(request):
    #show all albums in chronological order of it's upload
    albums = Album.objects.all()
    logger.info('Default page for user')
    return render(request, 'music_nation/home.html',{'albums':albums})

#........................................................#

def profile_detail(request, username):
    # show all albums of the artist
    albums = get_object_or_404(User, username=username)
    albums = albums.albums.all()
    logger.info(f'{username} locate in profile of "{User.username}"')
    return render(request, 'music_nation/artist_detail.html', {'albums':albums, 'username':username})

#........................................................#

@login_required
def add_album(request, username):
    user = get_object_or_404(User, username=username)
    #only currently logged in user can add album else will be redirected to home
    if user == request.user:
        if request.method == 'POST':
            form = NewAlbum(request.POST, request.FILES)
            if form.is_valid():
                # form.save(commit='False')
                album = Album.objects.create(
                    album_logo=form.cleaned_data.get('album_logo'),
                    album_name=form.cleaned_data.get('album_name'),
                    album_genre=form.cleaned_data.get('album_genre'),
                    uploaded_on = timezone.now(),
                    album_artist = request.user
                )
                logger.info(f'{username} add new album "{album.album_name}"')
                return redirect('music_nation:profile_detail', username=request.user)
        else:
            form = NewAlbum()
        return render(request, 'music_nation/add_new_album.html', {'form':form})
    else:
        return redirect('music_nation:profile_detail', username=user)

#........................................................#

def album_detail(request,username, album):
    #show album details here. single album's details.
    album = get_object_or_404(Album, album_name=album)
    songs = get_object_or_404(User, username=username)
    songs = songs.albums.get(album_name=str(album))
    songs = songs.songs.all()
    logger.info(f'{username} locate in album "{album}"')
    return render(request, 'music_nation/album_detail.html', {'songs':songs, 'album':album, 'username':username
    })

#........................................................#

def signup(request):
    logger.warning('Current template_name: signup.html')
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            message = 'You successfully made registration'
            logger.warning(message)
            return redirect('music_nation:home')
        else:
            message = 'Looks like a username with that email or password already exists'
            logger.warning(message)
            return render(request, 'music_nation/signup.html', {'form':form,'message':message})
    else:
        form = SignUpForm()
        return render(request, 'music_nation/signup.html', {'form':form})

#........................................................#

@login_required
def delete_album(request, username, album):
    user = get_object_or_404(User, username=username)
    if request.user == user:
        album_to_delete = get_object_or_404(User, username=username)
        album_to_delete = album_to_delete.albums.get(album_name=album)
        song_to_delete = album_to_delete.songs.all()
        for song in song_to_delete:
            song.delete_media()#deletes the song_file
        album_to_delete.delete_media()#deletes the album_logo
        album_to_delete.delete()#deletes the album from database
        logger.info(f'{username} delete album "{album.album_name}"')
        return redirect('music_nation:profile_detail', username=username)
    else:
        return redirect('music_nation:profile_detail', username=username)

#........................................................#

@login_required
def add_song(request, username, album):

    user = get_object_or_404(User, username=username)

    if request.user == user:

        album_get = Album.objects.get(album_name=album)

        if request.method == 'POST':
            form = NewSong(request.POST, request.FILES)
            if form.is_valid():
                # form.save(commit='False')
                song = Song.objects.create(
                    song_name = form.cleaned_data.get('song_name'),
                    song_file = form.cleaned_data.get('song_file'),
                    song_album = album_get
                )
                logger.info(f'{username} add new song {song.song_name} in album "{album}"')
                return redirect('music_nation:album_detail', username=username, album=album)

        else:
            form = NewSong()
            return render(request, 'music_nation/add_new_song.html', {'form':form})
    else:
        return redirect('music_nation:album_detail', username=username, album=album)

music_nation/templates/music_nation/add_new_album.html
{% extends 'music_nation/base.html' %}

{%block title%}
{%endblock%}
{%block content%}

  <div class="container">
    <h2 style="margin:30px;">Add new album here.</h2>
    <form method="POST" enctype="multipart/form-data">{# this field is important for file upload #}
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="save btn btn-default">Save</button>
    </form>
  </div>

{%endblock%}

music_nation/templates/music_nation/add_new_song.html
{% extends 'music_nation/base.html' %}

{%block title%}
{%endblock%}
{%block content%}

  <div class="container">
    <h2 style="margin:30px;">Add new song here.</h2>
    <form method="POST" enctype="multipart/form-data">{# this field is important for file upload #}
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="save btn btn-default">Save</button>
    </form>
  </div>

{%endblock%}

music_nation/templates/music_nation/album_detail.html
{% extends 'music_nation/base.html' %}

{%block title%}
{%endblock%}
{%block content%}
  <ul class="album-list">
    <h2>{{ album.album_name }}</h2>
    {% if album.album_artist == user %}
    <a href="{% url 'music_nation:delete_album' username album %}">Delete</a>/
    <a href="{% url 'music_nation:add_song' username album %}">Add new song</a>
    {% endif %}


    {% for song in songs %}
      <li >
        {{song.song_name}}<br/>
        <audio controls>
          <source src="{{ song.song_file.url }}" type="audio/mp3">
        </audio>
      </li><hr/>
    {% endfor %}
  </ul>
{%endblock%}

music_nation/templates/music_nation/artist_detail.html
{% extends 'music_nation/base.html' %}

{%block title%}
{%endblock%}
{%block content%}


<div class="container">

  {% for album in albums %}

      <h2 ><a href="{% url 'music_nation:album_detail' username album %}">{{album.album_name}}</a></h2>
    {% if album.album_artist == user %}
      <a href="{% url 'music_nation:delete_album' username album %}">Delete</a>
    {% endif %}
    {% for song in album.songs.all %}
      <li style="list-style-type: none; margin-left:70px;">{{song.song_name}}<br/>
        <audio controls>
          <source src="{{ song.song_file.url }}" type="audio/mp3">
        </audio>
      </li>
    {% endfor %}
    <hr/>
  {% endfor %}
</div>

{%endblock%}

music_nation/templates/music_nation/base.html
{% load static %}
<html>
  <head>
    <title>{%block title%}MusicNation{%endblock%}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'music_nation/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music_nation/css/music_nation.css' %}">
  </head>
  <body>
    <div >
      <header>
        <nav >
          <ul class="bglight">
            <li class="li-left">
              <a class="base-a-img" href="{% url 'music_nation:home' %}">
                <img src="{%static 'music_nation/img/logo.png' %}" style="width:50px;" alt="logo">
              </a>
            </li>
            {% if user.is_authenticated %}
            <li class="li-right">
              <a class="base-a" href="{% url 'music_nation:logout' %}">LogOut</a>
            </li>
            <li class="li-right">
              <a class="base-a" href="{% url 'music_nation:add_album' user %}">Add Album</a>
            </li>
            <li class="li-right">
              <a class="base-a" href="{% url 'music_nation:profile_detail' user %}">{{ user.username }}</a>
            </li>
            {% else %}
            <li class="li-right">
              <a class="base-a" href="{% url 'music_nation:login' %}">Login</a>
            </li>
            <li class="li-right">
              <a class="base-a" href="{% url 'music_nation:signup' %}">SignUp</a>
            </li>
            {% endif %}
          </ul>
        </nav>
      </header>
    </div>
    <div>
      {%block content%}
      {%endblock%}
    </div>

  </body>
</html>

music_nation/templates/music_nation/home.html
{% extends 'music_nation/base.html' %}

{%block title%}
{%endblock%}
{%block content%}
<pre>
SUDO username : bunny
password : bunny@123
email : bunny@carrots.com

artists password : artist@123
artist username : &lt;capitalized_artist_first_name&gt;_&lt;capitalized_artist_last_name&gt;
</pre><hr/>
<div>
  <ul class="home-list">
    {% for album in albums %}
      <li >
        <span><a class="home-a" href="{% url 'music_nation:album_detail' username=album.album_artist album=album.album_name %}">
          <img src="{{ album.album_logo.url }}" style="width:100px">
        </a></span>
         <span style="color:#007bff;">{{album.album_name}} by</span>
        <a class="home-a" href="{% url 'music_nation:profile_detail' username=album.album_artist %}">
          {{album.album_artist}}
        </a>
      </li><hr/>
    {% endfor %}
  </ul>
</div>

{%endblock%}

music_nation/templates/music_nation/login.html
{% extends 'music_nation/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h3><strong>You are already logged in</strong></h3>
<small>Do you want to <a href="{% url 'music_nation:logout' %}"><strong>LogOut</strong></a></small>

{% else %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}"
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endif %}
{% endblock %}

music_nation/templates/music_nation/signup.html
{% extends 'music_nation/base.html' %}

{% block title %}SignUp{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h3><strong>You will have to logout and sign in as a new user</strong></h3>
<small>Do you want to <a href="{% url 'music_nation:logout' %}"><strong>LogOut</strong></a></small>

{% else %}
      {% if message %}
              <li style="list-style-type:none;"><h3><strong>{{ message }}</strong></h3></li>
      {% endif %}
  <h2>SignUp</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">SignUp</button>
  </form>
{% endif %}
{% endblock %}